(require '[buddy.hashers :as hashers])

(println "=== GERADOR DE HASH DE SENHA ===")
(println "")
(println "Senha: Admin@123")
(println "Hash:" (hashers/encrypt "Admin@123"))
(println "")
(println "Copie o hash acima e execute no CockroachDB:")
(println "")
(println "UPDATE users SET password_hash = '<COLE_O_HASH_AQUI>' WHERE role = 'super-admin';")
